spring:
  profiles:
    active: default,development

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://leo-test-db.cac89ytu2lie.us-east-1.rds.amazonaws.com/leo_test_database?characterEncoding=utf-8
    username: leo_dev
    password: Hello12345
    test-on-borrow: true
    validation-query: select 1 from dual

